tossctr_toy:
    data_root: ../data
    data_format: csv
    train_data: ../data/toy/train_toy.csv
    valid_data: ../data/toy/train_toy.csv
    test_data: ../data/toy/train_toy.csv
    min_categr_count: 1
    feature_cols:
        - name: ["gender", "age_group", "inventory_id", "day_of_week", "hour"]
          active: True
          dtype: str
          type: categorical
        - name: ["l_feat_1", "l_feat_2", "l_feat_3", "l_feat_4", "l_feat_5", "l_feat_6", "l_feat_7", "l_feat_8", "l_feat_9", "l_feat_10",
                 "l_feat_11", "l_feat_12", "l_feat_13", "l_feat_14", "l_feat_15", "l_feat_16", "l_feat_17", "l_feat_18", "l_feat_19", "l_feat_20",
                 "l_feat_21", "l_feat_22", "l_feat_23", "l_feat_24", "l_feat_25", "l_feat_26", "l_feat_27",
                 "feat_e_1", "feat_e_2", "feat_e_3", "feat_e_4", "feat_e_5", "feat_e_6", "feat_e_7", "feat_e_8", "feat_e_9", "feat_e_10",
                 "feat_d_1", "feat_d_2", "feat_d_3", "feat_d_4", "feat_d_5", "feat_d_6",
                 "feat_c_1", "feat_c_2", "feat_c_3", "feat_c_4", "feat_c_5", "feat_c_6", "feat_c_7", "feat_c_8",
                 "feat_b_1", "feat_b_2", "feat_b_3", "feat_b_4", "feat_b_5", "feat_b_6",
                 "feat_a_1", "feat_a_2", "feat_a_3", "feat_a_4", "feat_a_5", "feat_a_6", "feat_a_7", "feat_a_8", "feat_a_9", "feat_a_10",
                 "feat_a_11", "feat_a_12", "feat_a_13", "feat_a_14", "feat_a_15", "feat_a_16", "feat_a_17", "feat_a_18"]
          active: True
          dtype: float
          type: numeric
          normalizer: MinMaxScaler
        - name: "seq"
          active: True
          dtype: str
          type: sequence
          splitter: ","
          max_len: 50
          feature_encoder: null
    label_col:
        name: "clicked"
        dtype: float

tossctr_full:
    data_root: ../data
    data_format: csv
    train_data: ../data/processed/train_full.csv
    valid_data: ../data/processed/val_full.csv
    test_data: ../data/processed/test_full.csv
    min_categr_count: 1
    feature_cols:
        - name: ["gender", "age_group", "inventory_id", "day_of_week", "hour"]
          active: True
          dtype: str
          type: categorical
        - name: ["l_feat_1", "l_feat_2", "l_feat_3", "l_feat_4", "l_feat_5", "l_feat_6", "l_feat_7", "l_feat_8", "l_feat_9", "l_feat_10",
                 "l_feat_11", "l_feat_12", "l_feat_13", "l_feat_14", "l_feat_15", "l_feat_16", "l_feat_17", "l_feat_18", "l_feat_19", "l_feat_20",
                 "l_feat_21", "l_feat_22", "l_feat_23", "l_feat_24", "l_feat_25", "l_feat_26", "l_feat_27",
                 "feat_e_1", "feat_e_2", "feat_e_3", "feat_e_4", "feat_e_5", "feat_e_6", "feat_e_7", "feat_e_8", "feat_e_9", "feat_e_10",
                 "feat_d_1", "feat_d_2", "feat_d_3", "feat_d_4", "feat_d_5", "feat_d_6",
                 "feat_c_1", "feat_c_2", "feat_c_3", "feat_c_4", "feat_c_5", "feat_c_6", "feat_c_7", "feat_c_8",
                 "feat_b_1", "feat_b_2", "feat_b_3", "feat_b_4", "feat_b_5", "feat_b_6",
                 "feat_a_1", "feat_a_2", "feat_a_3", "feat_a_4", "feat_a_5", "feat_a_6", "feat_a_7", "feat_a_8", "feat_a_9", "feat_a_10",
                 "feat_a_11", "feat_a_12", "feat_a_13", "feat_a_14", "feat_a_15", "feat_a_16", "feat_a_17", "feat_a_18"]
          active: True
          dtype: float
          type: numeric
          normalizer: MinMaxScaler
        - name: "seq"
          active: True
          dtype: str
          type: sequence
          splitter: ","
          max_len: 50
          feature_encoder: null
    label_col:
        name: "clicked"
        dtype: float

